### PR TITLE
fix issue after creating nagios file

### PR DESCRIPTION
**Pull request by sirkubax**
1. There was an error:
UnboundLocalError: local variable 'nagios_probe' referenced before assignment

2. Ignore args '-h host -p port' in nagios args parsing (did cause wrong output)

---
indention in the code formatting are tricky :/

### CODE REVIEW

**Comment by ideawu** [comment]
Hi, please use TAB to indent.

**Comment by ideawu** [comment]
I didn't noticed that your code are indent with spaces, so it must be changed to TAB indent when any update.

**Comment by sirkubax** [comment]
Had to change my vim setup :P
Should be in 'project format' now

**Comment by ideawu** [comment]
merged. but I dont't get an `UnboundLocalError: local variable 'nagios_probe' referenced before assignment` error before this merge, it works well for me.

**Pull request merged**
