### PR TITLE
Binary data to display as string escaped in ssdb-cli

### PR DESCRIPTION
**Pull request by cuixin**
hi, all response data translated by string_escaped function.
So, you can copy it from the terminal, and import the data by import tool.

### CODE REVIEW

**Comment by ideawu** [comment]
Hi, it is wrong to escape any data in a SDK, because SSDB is binary compatible. It is the user's responsible to choose any way he want to display any data.

You should never think of this totally WRONG thing! Man, you should inspect your own mind.

**Comment by ideawu** [comment]
If you want to escape binary data with ssdb-cli, see the help message:

```
ssdb 127.0.0.1:8888> help

# display ssdb-server status
	info
# escape/do not escape response data
	: escape yes|no
# export/import
	export [-i] out_file
		-i	interactive mode
	import in_file

see http://ssdb.io/docs/php/ for commands details

press 'q' and Enter to quit.
```

**Comment by cuixin** [comment]
hi, I know what you mean.
I've tried to set escape option on ./ssdb-cli. But it doesn't work. Binary data cannot string escaped yet. Was my command wrong?
```
ssdb 127.0.0.1:8888> :escape yes
  Escape response
ssdb 127.0.0.1:8888> 
```

**Comment by ideawu** [comment]
Hi, it is a bug in ssdb-cli.cpy, I just fixed it. Thank you.

close this PR.

**Pull request closed without merging**
