### PR TITLE
SSDB.py refactoring

### PR DESCRIPTION
**Pull request by deslum**
#### Refactoring

* Remove excess **pass** statements
* Compare long **if...or** on list 

       `if cmd in ['zscan','zrscan','zrange','zrrange','zpop_front','zpop_back']:`

* Delete excess conversions str(), typle()

Code tested on demo.py and my home project

### CODE REVIEW

**Comment by deslum** [comment]
#### My TODO list:

* Remake exceptions input for successful debugging
* Move the duplicate code in methods
* Create support with gevent greenlets
* Make reconnect if the connection with SSDB server is lost

Code tested on demo.py and my home project

**Comment by ideawu** [comment]
Hi, SSDB.py is automatically generated by cpy. You can see this at the beginning of it:

```
# encoding=utf-8
# Generated by cpy
# 2015-04-20 14:38:56.338378
```

**Comment by deslum** [comment]
I'm know what SSDB.py generated by cpy. But this is client contain a lot of excess code. I would like to add some features:

Support gevent pool for multiprocessing.
Raise except if connection close. Now, if the connection is lost, except not generated and method return None Connect is closed. This is not correct.
Methods must returns list for parse method return.

I can't develop this is features while code not refactoring and contain a lot of excess code.

Thanks.

**Comment by ideawu** [comment]
Hi, @deslum:

1. the recommented way to use SSDB.py is to create separated connection for each thread/process.
2. you choose your way.
3. the parse() do return list or null.

I think you can create a new repository to develop, I would like to add you repository to the client list at: http://ssdb.io/docs/clients.html

**Comment by deslum** [comment]
Ok, thanks

**Pull request closed without merging**
