### PR TITLE
Fix homebrew build

### PR DESCRIPTION
**Pull request by chenrui333**
reverts #1374

### CODE REVIEW

**Comment by geert-hendrickx-be** [comment]
Does this diff work for you? (relative to ssdb master branch)
It runs ssdb-cli from the tools' Makefile rather than the main one, so the relative paths are guaranteed.

```
diff --git a/Makefile b/Makefile
index 12519ef..fa5c8b3 100644
--- a/Makefile
+++ b/Makefile
@@ -14,7 +14,7 @@ all:
 	cd src/client; ${MAKE}
 	cd src/ssdb; ${MAKE}
 	cd src; ${MAKE}
-	cd tools; ${MAKE}; ./ssdb-cli -v > /dev/null
+	cd tools; ${MAKE}
 
 .PHONY: ios
 	
diff --git a/tools/Makefile b/tools/Makefile
index d206e8c..fec386a 100644
--- a/tools/Makefile
+++ b/tools/Makefile
@@ -11,6 +11,7 @@ all: ssdb-bench.o ssdb-dump.o ssdb-repair.o leveldb-import.o ssdb-migrate.o
 	${CXX} -o ssdb-repair ssdb-repair.o ${OBJS} ${UTIL_OBJS} ${CLIBS}
 	${CXX} -o leveldb-import leveldb-import.o ${OBJS} ${UTIL_OBJS} ${CLIBS}
 	${CXX} -o ssdb-migrate ssdb-migrate.o ../api/cpp/libssdb-client.a ../src/util/libutil.a
+	./ssdb-cli -v > /dev/null
 
 ssdb-migrate.o: ssdb-migrate.cpp
 	${CXX} ${CFLAGS} -I../api/cpp -c ssdb-migrate.cpp
```
@ideawu or is there a better way to convert the cpy code to python (byte)code during build?

**Comment by geert-hendrickx-be** [comment]
Hi

This means that the original issue that https://github.com/ideawu/ssdb/pull/1374 intended to fix is now back:

If ssdb is installed by root, then an unprivileged user cannot run ssdb-cli because he has no privileges to write the .py/.pyc files generated from the .cpy code.
root needs to invoke ssdb-cli at least once after installation, my change made this part of the Makefile build/install.

**Comment by ideawu** [comment]
Hi, I will add these to Makefile:

```
install:
    chmod 777 ${PREFIX}/_cpy_
```

**Comment by ideawu** [comment]
https://github.com/ideawu/ssdb/commit/61ae2cef97693a0fab9689883a1189900d99a21f

**Comment by geert-hendrickx-be** [comment]
Ehh no, that is https://github.com/ideawu/ssdb/pull/1330 back again.  You should **never** make executables world-writable, that is a serious security issue!

The py code needs to be generated just once, this should be done at build or install time, no later.

**Comment by ghen2** [comment]
Can you please revert this `chmod 777`?

**Review by limenpchuolto112-creator — APPROVED** [review]

**Pull request merged**
